[package]
name = "gui-slint-template"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
slint = "=1.13.1"
smol_str = "=0.3.2"

[build-dependencies]
slint-build = "=1.13.1"
cc = "1.0"

